services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD} # En variables de entorno
    ports:
      - "1433:1433"
    volumes:
      - test_sql_data:/var/opt/mssql #Pesistencia de datos
      - ./backups:/backups #Para backups manuales

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - sqlserver
    entrypoint: /bin/bash -c "
      sleep 15 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${DB_PASSWORD} -Q 'IF DB_ID('DIGITALARS_DB') IS NULL CREATE DATABASE DIGITALARS_DB;'"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - sqlserver
    volumes:
      - ./infra/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "9273:9273"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./infra/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  backend:
    build:
      context: ./backend/scr/DigitalArs
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080   
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DIGITALARS_DB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver
volumes:
  test_sql_data:
  grafana_data:
