global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'sqlserver'
    static_configs:
      - targets: ['telegraf:9273']

      