CREATE DATABASE DIGITALARS_DB;
GO

USE DIGITALARS_DB;
GO

CREATE TABLE ROL(
	ID_ROL INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ROL VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASS NVARCHAR(150) NOT NULL,
	CREATION_DATE DATETIME DEFAULT GETDATE(),
	ID_ROL INT NOT NULL,

	CONSTRAINT FK_ROL_CUENTA
		FOREIGN KEY (ID_ROL)
		REFERENCES ROL(ID_ROL)
);
GO

CREATE TABLE CUENTA (
	ID_CUENTA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	SALDO FLOAT NOT NULL DEFAULT(0),
	ALIAS VARCHAR(50) NULL UNIQUE,
	CBU VARCHAR(22) NULL UNIQUE,

	CONSTRAINT FK_CUENTA_USUARIO
		FOREIGN KEY(ID_USUARIO)
		REFERENCES USUARIO (ID_USUARIO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
GO

CREATE TABLE TRANSACCIONES (
	ID_TRANSACCION INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CUENTA_ORIGEN INT NOT NULL,
	ID_CUENTA_DESTINO INT NOT NULL,
	MONTO FLOAT NOT NULL,
	FECHA DATETIME NOT NULL DEFAULT GETDATE(),

	CONSTRAINT FK_TRANSACCION_ORIGEN
		FOREIGN KEY (ID_CUENTA_ORIGEN)
		REFERENCES CUENTA(ID_CUENTA),

	CONSTRAINT FK_TRANSACCION_DESTINO
		FOREIGN KEY (ID_CUENTA_DESTINO)
		REFERENCES CUENTA(ID_CUENTA),
);
GO

CREATE TABLE PLAZO_FIJO (
	ID_PLAZOFIJO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CUENTA INT NOT NULL,
	MONTO FLOAT NOT NULL,
	PLAZO INT NOT NULL,														/* plazo en dias: 30, 60, 90 */
	TASA_INTERES FLOAT NOT NULL,
	FECHA_INICIO DATETIME NOT NULL DEFAULT GETDATE(),
	FECHA_VENCIMIENTO AS DATEADD(DAY, PLAZO, FECHA_INICIO) PERSISTED,
	INTERES_GENERADO FLOAT NOT NULL DEFAULT(0),
	ESTADO VARCHAR(20) NOT NULL,

	CONSTRAINT ENUM_PLAZO_FIJO_ESTADO
		CHECK (ESTADO IN ('ERROR','VALIDO','EN PROCESO')),

	CONSTRAINT FK_PLAZO_FIJO_CUENTA
		FOREIGN KEY (ID_CUENTA)
		REFERENCES CUENTA(ID_CUENTA)
		ON DELETE CASCADE,
);
GO

INSERT INTO ROL(NOMBRE_ROL)
VALUES('ADMIN');

INSERT INTO ROL(NOMBRE_ROL)
VALUES('NORMAL');

-- Admin
-- Contraseña: 12341234
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('admin1', 'admin1@gmail.com', 'AQAAAAIAAYagAAAAEM6fUMzmUoPJX6f45bMFWCrNOUOKoyvZOdvWbOcroxiViiHuKyQ9ld423g45qZnuwg==', 1);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.admin.1', 1234567890123456);
GO

-- Usuario 1
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Juan P rez', 'juan.perez@mail.com', 'AQAAAAIAAYagAAAAEMwerU9rI6704Hpt7Xmz+lZsTCGwV9KeVBXxH17R/merLXaovqWco7ySQvoAODDBhQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.juan.perez', 1234567890000001);
GO

-- Usuario 2
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mar a G mez', 'maria.gomez@mail.com', 'AQAAAAIAAYagAAAAEOVbyrLGHjDWRBbPdNX6PLweN1SdeFU2D2neUEcoC4dBzXVtd26Kqe6B6yStNl/jEg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.maria.gomez', 1234567890000002);
GO

-- Usuario 3
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Carlos L pez', 'carlos.lopez@mail.com', 'AQAAAAIAAYagAAAAEDUflfk7t9vxhO2mS0qbRG4O33KtfBDSuPU5cB31cr0JwwS3Xdzn73Ekdg1sjEBg8g==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.carlos.lopez', 1234567890000003);
GO

-- Usuario 4
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Ana Mart nez', 'ana.martinez@mail.com', 'AQAAAAIAAYagAAAAECQoQcBFOSu1fSsBHyW8zY7TGesdluEJzivKNfKQgW8wj5gxbd3ugKHzN9ZmKUxHjg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.ana.martinez', 1234567890000004);
GO

-- Usuario 5
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Pedro Ram rez', 'pedro.ramirez@mail.com', 'AQAAAAIAAYagAAAAEIvsRbt7fwaXZVvfloDuOgt2Jk2i7hwiNYFgCv9ZDwwXjn6LZQ5mx49H5HFpI1rkMg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.pedro.ramirez', 1234567890000005);
GO

-- Usuario 6
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Laura S nchez', 'laura.sanchez@mail.com', 'AQAAAAIAAYagAAAAEHqBeqxjppyqmZH+d7rJIAUQWddxZojj0mcX9+M/VCM2tDccabKsYal2LK66mltJZQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.laura.sanchez', 1234567890000006);
GO

-- Usuario 7
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Diego Torres', 'diego.torres@mail.com', 'AQAAAAIAAYagAAAAEBR8NpOzR/PkUaYDqyzTS+u8YiQ5COf1aOWsc6F442Fpyt/5tXQrUFyFWNE8NnMzkQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.diego.torres', 1234567890000007);
GO

-- Usuario 8
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Camila D az', 'camila.diaz@mail.com', 'AQAAAAIAAYagAAAAELWo4JODUoTtp4V4dEtsneovyTP9KgkWk2iM8JKx6ifYS2ZBdAZn/1MRQlkO7vCtQg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.camila.diaz', 1234567890000008);
GO

-- Usuario 9
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Luc a Romero', 'lucia.romero@mail.com', 'AQAAAAIAAYagAAAAEAUUypLf6w33Kh8cw+1vdjnb1Q5tMsj1MDymiHESMozOx3+hBekj51CaFFhtIGjf5Q==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.lucia.romero', 1234567890000009);
GO

-- Usuario 10
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Javier Herrera', 'javier.herrera@mail.com', 'AQAAAAIAAYagAAAAEK8QEMdK8P8nGj372ALbPm0ay1pI/+u7/uosWl9ZjsTO/tkU7t5F0gDUE2MFW6mhmA==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.javier.herrera', 1234567890000010);
GO

-- Usuario 11
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Valentina Rojas', 'valentina.rojas@mail.com', 'AQAAAAIAAYagAAAAEA6Wmz1n2PxpJh7gz809nmajFO5NSCegU7mna1AuwByik3OAjLlf6nLiFr4j0TDIlg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.valentina.rojas', 1234567890000011);
GO

-- Usuario 12
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mart n Castro', 'martin.castro@mail.com', 'AQAAAAIAAYagAAAAEFUE5fHHO3DR4TLNKK9Igs2YYih6WMd/uXNiaCzNnGBUIPNuOUrVQh5k9FtQjiOOhQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.martin.castro', 1234567890000012);
GO

-- Usuario 13
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Sof a Morales', 'sofia.morales@mail.com', 'AQAAAAIAAYagAAAAEA1f/Z6n7nefWC1Mlep25A1qILY0y+q6lqiBJerjTWpCuEuRQEd7gSHU+4sFn6cKlQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.sofia.morales', 1234567890000013);
GO

-- Usuario 14
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Federico Aguirre', 'federico.aguirre@mail.com', 'AQAAAAIAAYagAAAAEKc0evB4xaEHMIz+gjqxawPaArJPoFZJpfoNfF5gS3qy4D5YX+ZFL4soaVbtT759Rg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.federico.aguirre', 1234567890000014);
GO

-- Usuario 15
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Isabella Paredes', 'isabella.paredes@mail.com', 'AQAAAAIAAYagAAAAECa5sPw0x/jFpuGT9919e4UqttgFSigGwGrefsdKhsk/WN61xztDI/mXDs71uWbD9w==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.isabella.paredes', 1234567890000015);
GO

-- Usuario 16
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Tom s Ib  ez', 'tomas.ibanez@mail.com', 'AQAAAAIAAYagAAAAEFzm/67u/GhHxZq3sQN4K0QF6lDwxWr3I3mYLfSI4JWldLs85aVQXFCSLypOSQ+R/Q==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.tomas.ibanez', 1234567890000016);
GO

-- Usuario 17
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Emilia Vera', 'emilia.vera@mail.com', 'AQAAAAIAAYagAAAAEO+LUg1Y1n+sGDWRwXdbSG1AZOPDfuCbyZUEwf340D+NCoO7gmZfMHxRtM8X7A3tag==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.emilia.vera', 1234567890000017);
GO

-- Usuario 18
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mat as Salas', 'matias.salas@mail.com', 'AQAAAAIAAYagAAAAEBbSQqJmu8Lrj8i46eDg7j5lly5ioelpYEfKSsnRWx0KzcZ7zqYjs+i8ehuvP3IEHQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.matias.salas', 1234567890000018);
GO

-- Usuario 19
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Agustina Godoy', 'agustina.godoy@mail.com', 'AQAAAAIAAYagAAAAEOD0bOOaUP4FSEB2Jx/mqS42N3PcFwRkTJduyCQ7qjqNk/YtYvtQTH0/P1Yq/O85xg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.agustina.godoy', 1234567890000019);
GO

-- Usuario 20
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Nicol s Silva', 'nicolas.silva@mail.com', 'AQAAAAIAAYagAAAAECSl2E/V+gWIuWgDTu5FQmLZ7fkNGSsag0fTSOcBYbqcyvej2OONitZRNbFahngpmg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.nicolas.silva', 1234567890000020);
GO

-- Usuario 21
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Florencia Navarro', 'florencia.navarro@mail.com', 'AQAAAAIAAYagAAAAEAiH86SZUh8377oHlZjrYRGqjnkVUn8Dv5sMGY0T0S1B9QrdIzhom6UkWG5796nmXQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.florencia.navarro', 1234567890000021);
GO

-- Usuario 22
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Sebasti n Correa', 'sebastian.correa@mail.com', 'AQAAAAIAAYagAAAAEI+YwRwqo+jzaINvxtGVi4D3k98F8SHEHWLT5Y13yC6WeIl9t4OI1S6xCpPQUiwwBQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.sebastian.correa', 1234567890000022);
GO

-- Usuario 23
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Julieta M ndez', 'julieta.mendez@mail.com', 'AQAAAAIAAYagAAAAEKANGvWij4Zr4c3esvv0oEwvlhZYI+3IzXwb9oueCGbTt7llPwo+ZDo84O2zRc0mIg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.julieta.mendez', 1234567890000023);
GO

-- Usuario 24
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Gonzalo Far as', 'gonzalo.farias@mail.com', 'AQAAAAIAAYagAAAAEAf8rBH//6Ei7JbcZH3WUWzpthHeXJZeCi8/za7+BKM+U6WMSi+dWRxK5dwfrSGiKQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.gonzalo.farias', 1234567890000024);
GO

-- Usuario 25
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Milagros Quiroga', 'milagros.quiroga@mail.com', 'AQAAAAIAAYagAAAAEEa4Y5ndPPXf7OLBoJw33fpRAzcv5not0LN2sdk48Uw2FnrTVLbhull85VHRHw8ReA==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.milagros.quiroga', 1234567890000025);
GO

-- Usuario 26
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Ramiro Pe a', 'ramiro.pena@mail.com', 'AQAAAAIAAYagAAAAEFwMcKWBZN3gy2I4vWohmNiYqc0BmHHeQW+JkyLMn+NmcKYEbBVM1Ss7R8Yi/tgSEg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.ramiro.pena', 1234567890000026);
GO

-- Usuario 27
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Martina Ruiz', 'martina.ruiz@mail.com', 'AQAAAAIAAYagAAAAEAwlJM7hnvG0GKZwyusxfCaM56IL4tBSlQE97gNr9Ge6JaZemJoFdEBu9O7QiPRZrA==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.martina.ruiz', 1234567890000027);
GO

-- Usuario 28
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Leandro Molina', 'leandro.molina@mail.com', 'AQAAAAIAAYagAAAAELCr6sr6YnUHTEpQW7TUikZcS2nyo4uybQWNpldiLgvwdEYp1a7daxzHLHPOTlwGCg==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.leandro.molina', 1234567890000028);
GO

-- Usuario 29
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Bianca Ayala', 'bianca.ayala@mail.com', 'AQAAAAIAAYagAAAAECkqfZ2pMq++0OEzBcdpG3n+8uPYqW+khHxmncVTI9UIadGEhJVJbzqFJxHZUuKtEQ==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.bianca.ayala', 1234567890000029);
GO

-- Usuario 30
-- Contraseña: clave123
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Facundo Del R o', 'facundo.delrio@mail.com', 'AQAAAAIAAYagAAAAEIwM1ewRENjzXy5QAvCRgmjD02IAmH80NdXC8NmJ5p/u8pboR9Y92BIkxPKX6Vue2w==', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.facundo.delrio', 1234567890000030);
GO

-- transacciones
INSERT INTO TRANSACCIONES (ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, MONTO, TIPO)
VALUES (2, 3, 1500),
       (3, 2, 1500),
       (4, 5, 2000),
       (5, 4, 2000),
       (6, 7, 500),
       (7, 6, 500),
       (8, 9, 750),
       (9, 8, 750),
       (10, 11, 1000),
       (11, 10, 1000);
GO

-- plazos fijos
INSERT INTO PLAZO_FIJO (ID_CUENTA, MONTO, PLAZO, TASA_INTERES, ESTADO)
VALUES
(2, 5000, 30, 3.5, 'VALIDO'),
(3, 3000, 60, 4.2, 'VALIDO'),
(4, 7000, 90, 5.0, 'EN PROCESO'),
(5, 2500, 30, 3.5, 'VALIDO'),
(6, 8000, 60, 4.1, 'VALIDO'),
(7, 1500, 90, 5.2, 'VALIDO'),
(8, 4000, 30, 3.3, 'VALIDO'),
(9, 3500, 60, 4.0, 'VALIDO'),
(10, 1000, 90, 5.5, 'EN PROCESO'),
(11, 2000, 30, 3.2, 'VALIDO');
GO