CREATE DATABASE DIGITALARS_DB;
GO

USE DIGITALARS_DB;
GO

CREATE TABLE ROL(
	ID_ROL INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ROL VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASS VARCHAR(50) NOT NULL,
	CREATION_DATE DATETIME DEFAULT GETDATE(),
	ID_ROL INT NOT NULL,

	CONSTRAINT FK_ROL_CUENTA
		FOREIGN KEY (ID_ROL)
		REFERENCES ROL(ID_ROL)
);
GO

CREATE TABLE CUENTA (
	ID_CUENTA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	SALDO FLOAT NOT NULL DEFAULT(0),
	ALIAS VARCHAR(50) NULL UNIQUE,
	CBU VARCHAR(22) NULL UNIQUE,

	CONSTRAINT FK_CUENTA_USUARIO
		FOREIGN KEY(ID_USUARIO)
		REFERENCES USUARIO (ID_USUARIO)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
GO

CREATE TABLE TRANSACCIONES (
	ID_TRANSACCION INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CUENTA_ORIGEN INT NOT NULL,
	ID_CUENTA_DESTINO INT NOT NULL,
	MONTO FLOAT NOT NULL,
	FECHA DATETIME NOT NULL DEFAULT GETDATE(),
	TIPO VARCHAR(50) NOT NULL,

	CONSTRAINT ENUM_TIPO
		CHECK (TIPO IN ('ENVIO','RECEPCION')),

	CONSTRAINT FK_TRANSACCION_ORIGEN
		FOREIGN KEY (ID_CUENTA_ORIGEN)
		REFERENCES CUENTA(ID_CUENTA),

	CONSTRAINT FK_TRANSACCION_DESTINO
		FOREIGN KEY (ID_CUENTA_DESTINO)
		REFERENCES CUENTA(ID_CUENTA),
);
GO

CREATE TABLE PLAZOFIJO (
	ID_PLAZOFIJO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_CUENTA INT NOT NULL,
	MONTO FLOAT NOT NULL,
	PLAZO INT NOT NULL,														/* plazo en dias: 30, 60, 90 */
	TASA_INTERES FLOAT NOT NULL,
	FECHA_INICIO DATETIME NOT NULL DEFAULT GETDATE(),
	FECHA_VENCIMIENTO AS DATEADD(DAY, PLAZO, FECHA_INICIO) PERSISTED,
	INTERES_GENERADO FLOAT NOT NULL DEFAULT(0),
	ESTADO VARCHAR(20) NOT NULL,

	CONSTRAINT ENUM_PLAZO_FIJO_ESTADO
		CHECK (ESTADO IN ('ERROR','VALIDO','EN PROCESO')),

	CONSTRAINT FK_PLAZO_FIJO_CUENTA
		FOREIGN KEY (ID_CUENTA)
		REFERENCES CUENTA(ID_CUENTA)
		ON DELETE CASCADE,
);
GO

INSERT INTO ROL(NOMBRE_ROL)
VALUES('ADMIN');

INSERT INTO ROL(NOMBRE_ROL)
VALUES('NORMAL');

-- Admin
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('admin1', 'admin1@gmail.com', '12341234', 1);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.admin.1', 1234567890123456);
GO

-- Usuario 1
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Juan P�rez', 'juan.perez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.juan.perez', 1234567890000001);
GO

-- Usuario 2
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mar�a G�mez', 'maria.gomez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.maria.gomez', 1234567890000002);
GO

-- Usuario 3
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Carlos L�pez', 'carlos.lopez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.carlos.lopez', 1234567890000003);
GO

-- Usuario 4
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Ana Mart�nez', 'ana.martinez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.ana.martinez', 1234567890000004);
GO

-- Usuario 5
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Pedro Ram�rez', 'pedro.ramirez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.pedro.ramirez', 1234567890000005);
GO

-- Usuario 6
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Laura S�nchez', 'laura.sanchez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.laura.sanchez', 1234567890000006);
GO

-- Usuario 7
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Diego Torres', 'diego.torres@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.diego.torres', 1234567890000007);
GO

-- Usuario 8
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Camila D�az', 'camila.diaz@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.camila.diaz', 1234567890000008);
GO

-- Usuario 9
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Luc�a Romero', 'lucia.romero@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.lucia.romero', 1234567890000009);
GO

-- Usuario 10
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Javier Herrera', 'javier.herrera@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.javier.herrera', 1234567890000010);
GO

-- Usuario 11
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Valentina Rojas', 'valentina.rojas@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.valentina.rojas', 1234567890000011);
GO

-- Usuario 12
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mart�n Castro', 'martin.castro@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.martin.castro', 1234567890000012);
GO

-- Usuario 13
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Sof�a Morales', 'sofia.morales@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.sofia.morales', 1234567890000013);
GO

-- Usuario 14
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Federico Aguirre', 'federico.aguirre@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.federico.aguirre', 1234567890000014);
GO

-- Usuario 15
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Isabella Paredes', 'isabella.paredes@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.isabella.paredes', 1234567890000015);
GO

-- Usuario 16
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Tom�s Ib��ez', 'tomas.ibanez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.tomas.ibanez', 1234567890000016);
GO

-- Usuario 17
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Emilia Vera', 'emilia.vera@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.emilia.vera', 1234567890000017);
GO

-- Usuario 18
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Mat�as Salas', 'matias.salas@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.matias.salas', 1234567890000018);
GO

-- Usuario 19
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Agustina Godoy', 'agustina.godoy@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.agustina.godoy', 1234567890000019);
GO

-- Usuario 20
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Nicol�s Silva', 'nicolas.silva@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.nicolas.silva', 1234567890000020);
GO

-- Usuario 21
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Florencia Navarro', 'florencia.navarro@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.florencia.navarro', 1234567890000021);
GO

-- Usuario 22
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Sebasti�n Correa', 'sebastian.correa@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.sebastian.correa', 1234567890000022);
GO

-- Usuario 23
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Julieta M�ndez', 'julieta.mendez@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.julieta.mendez', 1234567890000023);
GO

-- Usuario 24
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Gonzalo Far�as', 'gonzalo.farias@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.gonzalo.farias', 1234567890000024);
GO

-- Usuario 25
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Milagros Quiroga', 'milagros.quiroga@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.milagros.quiroga', 1234567890000025);
GO

-- Usuario 26
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Ramiro Pe�a', 'ramiro.pena@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.ramiro.pena', 1234567890000026);
GO

-- Usuario 27
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Martina Ruiz', 'martina.ruiz@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.martina.ruiz', 1234567890000027);
GO

-- Usuario 28
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Leandro Molina', 'leandro.molina@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.leandro.molina', 1234567890000028);
GO

-- Usuario 29
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Bianca Ayala', 'bianca.ayala@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.bianca.ayala', 1234567890000029);
GO

-- Usuario 30
INSERT INTO USUARIO (NOMBRE, EMAIL, PASS, ID_ROL)
VALUES ('Facundo Del R�o', 'facundo.delrio@mail.com', 'clave123', 2);
DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
INSERT INTO CUENTA (ID_USUARIO, SALDO, ALIAS, CBU)
VALUES (@ID_USUARIO, 10000.00, 'digitalars.facundo.delrio', 1234567890000030);
GO

-- transacciones
INSERT INTO TRANSACCIONES (ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, MONTO, TIPO)
VALUES (2, 3, 1500, 'ENVIO'),
       (3, 2, 1500, 'RECEPCION'),
       (4, 5, 2000, 'ENVIO'),
       (5, 4, 2000, 'RECEPCION'),
       (6, 7, 500, 'ENVIO'),
       (7, 6, 500, 'RECEPCION'),
       (8, 9, 750, 'ENVIO'),
       (9, 8, 750, 'RECEPCION'),
       (10, 11, 1000, 'ENVIO'),
       (11, 10, 1000, 'RECEPCION');
GO

-- plazos fijos
INSERT INTO PLAZO_FIJO (ID_CUENTA, MONTO, PLAZO, TASA_INTERES, ESTADO)
VALUES
(2, 5000, 30, 3.5, 'VALIDO'),
(3, 3000, 60, 4.2, 'VALIDO'),
(4, 7000, 90, 5.0, 'EN PROCESO'),
(5, 2500, 30, 3.5, 'VALIDO'),
(6, 8000, 60, 4.1, 'VALIDO'),
(7, 1500, 90, 5.2, 'VALIDO'),
(8, 4000, 30, 3.3, 'VALIDO'),
(9, 3500, 60, 4.0, 'VALIDO'),
(10, 1000, 90, 5.5, 'EN PROCESO'),
(11, 2000, 30, 3.2, 'VALIDO');
GO