// <auto-generated />
using System;
using DigitalArs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalArs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609001712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalArs.Models.Cuenta", b =>
                {
                    b.Property<int>("ID_CUENTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CUENTA"));

                    b.Property<string>("ALIAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("int");

                    b.Property<double>("SALDO")
                        .HasColumnType("float");

                    b.HasKey("ID_CUENTA");

                    b.ToTable("CUENTA");
                });

            modelBuilder.Entity("DigitalArs.Models.PlazoFijo", b =>
                {
                    b.Property<int>("ID_PLAZOFIJO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PLAZOFIJO"));

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FECHA_INICIO")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_CUENTA")
                        .HasColumnType("int");

                    b.Property<decimal>("INTERES_GENERADO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MONTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PLAZO")
                        .HasColumnType("int");

                    b.Property<decimal>("TASA_INTERES")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("fecha_vencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_PLAZOFIJO");

                    b.ToTable("PlazoFijo");
                });

            modelBuilder.Entity("DigitalArs.Models.Transaccion", b =>
                {
                    b.Property<int>("ID_TRANSACCION")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TRANSACCION"));

                    b.Property<DateTime>("FECHA")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_CUENTA_DESTINO")
                        .HasColumnType("int");

                    b.Property<int>("ID_CUENTA_ORIGEN")
                        .HasColumnType("int");

                    b.Property<double>("MONTO")
                        .HasColumnType("float");

                    b.HasKey("ID_TRANSACCION");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("DigitalArs.Models.Usuario", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<DateTime>("CREATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ROL")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
